// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelTour.API.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    partial class TravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelTour.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdultCount")
                        .HasColumnType("int");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourScheduleId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TotalPassengers = 2,
                            TotalPrice = 9000000m,
                            TourScheduleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPassengers = 2,
                            TotalPrice = 6000000m,
                            TourScheduleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TotalPassengers = 2,
                            TotalPrice = 10400000m,
                            TourScheduleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TotalPassengers = 2,
                            TotalPrice = 7600000m,
                            TourScheduleId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TotalPassengers = 3,
                            TotalPrice = 2700000m,
                            TourScheduleId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPassengers = 2,
                            TotalPrice = 9400000m,
                            TourScheduleId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TotalPassengers = 2,
                            TotalPrice = 6400000m,
                            TourScheduleId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TotalPassengers = 1,
                            TotalPrice = 3100000m,
                            TourScheduleId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TotalPassengers = 2,
                            TotalPrice = 11000000m,
                            TourScheduleId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            AdultCount = 0,
                            ChildCount = 0,
                            ContactEmail = "",
                            ContactName = "",
                            ContactPhone = "",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPassengers = 2,
                            TotalPrice = 1400000m,
                            TourScheduleId = 10,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.BookingAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingAttendees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn A",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            DateOfBirth = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị B",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            DateOfBirth = new DateTime(2002, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Văn C",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            DateOfBirth = new DateTime(2003, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Thị D",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            DateOfBirth = new DateTime(2004, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hoàng Văn E",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 6,
                            BookingId = 6,
                            DateOfBirth = new DateTime(2005, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Đỗ Thị F",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 7,
                            BookingId = 7,
                            DateOfBirth = new DateTime(2000, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Võ Văn G",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 8,
                            BookingId = 8,
                            DateOfBirth = new DateTime(2001, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bùi Thị H",
                            Type = "Child"
                        },
                        new
                        {
                            Id = 9,
                            BookingId = 9,
                            DateOfBirth = new DateTime(2002, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ngô Văn I",
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 10,
                            BookingId = 10,
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Admin",
                            Type = "Adult"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Đắm mình trong làn nước trong xanh...",
                            Name = "Tour Biển"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hành trình ngược dòng thời gian...",
                            Name = "Tour Di Sản - Văn Hóa"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dành cho những tâm hồn đam mê xê dịch...",
                            Name = "Tour Khám Phá"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Trải nghiệm nhịp sống bình dị...",
                            Name = "Tour Miền Tây"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chinh phục những đỉnh cao mây mờ...",
                            Name = "Tour Núi"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.ToTable("MediaAssets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Côn Đảo",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "ConDao.webp",
                            FileUrl = "/uploads/media/ConDao.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Côn Đảo 1",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "ConDao1.webp",
                            FileUrl = "/uploads/media/ConDao1.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Côn Đảo 2",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "ConDao2.webp",
                            FileUrl = "/uploads/media/ConDao2.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Đảo Phú Quý",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "DaoPhuQuy.webp",
                            FileUrl = "/uploads/media/DaoPhuQuy.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 5,
                            AltText = "Đảo Phú Quý 1",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "DaoPhuQuy1.webp",
                            FileUrl = "/uploads/media/DaoPhuQuy1.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 6,
                            AltText = "Đảo Phú Quý 2",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "DaoPhuQuy2.webp",
                            FileUrl = "/uploads/media/DaoPhuQuy2.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 7,
                            AltText = "Nha Trang",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "NhaTrang.webp",
                            FileUrl = "/uploads/media/NhaTrang.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 8,
                            AltText = "Nha Trang 1",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "NhaTrang1.webp",
                            FileUrl = "/uploads/media/NhaTrang1.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Nha Trang 2",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "NhaTrang2.webp",
                            FileUrl = "/uploads/media/NhaTrang2.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Phú Quốc",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "PhuQuoc.webp",
                            FileUrl = "/uploads/media/PhuQuoc.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Phú Quốc 1",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "PhuQuoc1.webp",
                            FileUrl = "/uploads/media/PhuQuoc1.webp",
                            UploadedById = 10
                        },
                        new
                        {
                            Id = 12,
                            AltText = "Phú Quốc 2",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "PhuQuoc2.webp",
                            FileUrl = "/uploads/media/PhuQuoc2.webp",
                            UploadedById = 10
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Tin du lịch",
                            Slug = "tin-du-lich"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Khuyến mãi",
                            Slug = "khuyen-mai"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Kinh nghiệm",
                            Slug = "kinh-nghiem"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ẩm thực",
                            Slug = "am-thuc"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Check-in",
                            Slug = "check-in"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Review",
                            Slug = "review"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Tips",
                            Slug = "tips"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Tin hot",
                            Slug = "tin-hot"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Du lịch quốc tế",
                            Slug = "du-lich-qt"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Blog",
                            Slug = "blog"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PublishedById")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublishedById");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Phú Quốc nổi tiếng với bãi Sao...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Slug = "bien-dep-phu-quoc",
                            Status = "Published",
                            Summary = "Danh sách bãi biển đẹp",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Top 5 bãi biển đẹp nhất Phú Quốc",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 120
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 3,
                            Content = "Đà Lạt là điểm đến lý tưởng...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Slug = "kinh-nghiem-da-lat",
                            Status = "Published",
                            Summary = "Hướng dẫn du lịch Đà Lạt",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Kinh nghiệm đi Đà Lạt tự túc",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 4,
                            Content = "Hải sản Nha Trang rất nổi tiếng...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Slug = "am-thuc-nha-trang",
                            Status = "Published",
                            Summary = "Top món ngon Nha Trang",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Ăn gì ở Nha Trang?",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 150
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 5,
                            Content = "Nếu may mắn bạn sẽ thấy tuyết...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Slug = "checkin-sapa",
                            Status = "Draft",
                            Summary = "Sapa mùa đông cực đẹp",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Check-in Sapa mùa tuyết",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 30
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 2,
                            Content = "Du lịch Đà Nẵng chưa bao giờ rẻ...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Slug = "tour-da-nang-gia-re",
                            Status = "Published",
                            Summary = "Combo tiết kiệm",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Tour Đà Nẵng giá rẻ",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 200
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 7,
                            Content = "Hà Giang là cung đường mơ ước...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Slug = "phuot-ha-giang",
                            Status = "Published",
                            Summary = "Checklist phượt",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Phượt Hà Giang cần chuẩn bị gì?",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 80
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            CategoryId = 6,
                            Content = "Phú Yên đang nổi lên...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Slug = "review-resort-phu-yen",
                            Status = "Published",
                            Summary = "Resort view biển",
                            ThumbnailUrl = "/uploads/media/PhuQuoc.webp",
                            Title = "Review resort Phú Yên",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 60
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CategoryId = 9,
                            Content = "Các địa điểm phù hợp gia đình...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Slug = "du-lich-gia-dinh",
                            Status = "Published",
                            Summary = "Gợi ý địa điểm",
                            ThumbnailUrl = "/uploads/media/ConDao1.webp",
                            Title = "Du lịch gia đình nên đi đâu?",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 140
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            CategoryId = 2,
                            Content = "Côn Đảo là điểm đến tâm linh...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Slug = "combo-con-dao",
                            Status = "Draft",
                            Summary = "Ưu đãi hot",
                            ThumbnailUrl = "/uploads/media/ConDao1.webp",
                            Title = "Combo Côn Đảo tiết kiệm",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 20
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            CategoryId = 10,
                            Content = "Bạn có thể đi Nhà thờ Đức Bà...",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Slug = "sai-gon-1-ngay",
                            Status = "Published",
                            Summary = "City tour HCM",
                            ThumbnailUrl = "/uploads/media/ConDao2.webp",
                            Title = "Khám phá Sài Gòn 1 ngày",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 300
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Du lịch biển",
                            Slug = "du-lich-bien"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Du lịch núi",
                            Slug = "du-lich-nui"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ẩm thực",
                            Slug = "am-thuc"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kinh nghiệm",
                            Slug = "kinh-nghiem"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Check-in đẹp",
                            Slug = "check-in-dep"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Review tour",
                            Slug = "review-tour"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phượt",
                            Slug = "phuot"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Resort",
                            Slug = "resort"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gia đình",
                            Slug = "gia-dinh"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khuyến mãi",
                            Slug = "khuyen-mai"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsTagMap", b =>
                {
                    b.Property<int>("NewsPostId")
                        .HasColumnType("int");

                    b.Property<int>("NewsTagId")
                        .HasColumnType("int");

                    b.HasKey("NewsPostId", "NewsTagId");

                    b.HasIndex("NewsTagId");

                    b.ToTable("NewsTagMaps");

                    b.HasData(
                        new
                        {
                            NewsPostId = 1,
                            NewsTagId = 1
                        },
                        new
                        {
                            NewsPostId = 2,
                            NewsTagId = 4
                        },
                        new
                        {
                            NewsPostId = 3,
                            NewsTagId = 3
                        },
                        new
                        {
                            NewsPostId = 4,
                            NewsTagId = 5
                        },
                        new
                        {
                            NewsPostId = 5,
                            NewsTagId = 10
                        },
                        new
                        {
                            NewsPostId = 6,
                            NewsTagId = 7
                        },
                        new
                        {
                            NewsPostId = 7,
                            NewsTagId = 8
                        },
                        new
                        {
                            NewsPostId = 8,
                            NewsTagId = 9
                        },
                        new
                        {
                            NewsPostId = 9,
                            NewsTagId = 10
                        },
                        new
                        {
                            NewsPostId = 10,
                            NewsTagId = 5
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Tour rất tuyệt!",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Khá ổn",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            TourId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Bình thường",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            TourId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Rất đáng tiền",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            TourId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Không như mong đợi",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            TourId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Dịch vụ tốt",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            TourId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Cảnh đẹp",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            TourId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Tạm được",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            TourId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Hài lòng",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            TourId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Rất thích",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            TourId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "CD001",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Description = "Thiên đường biển hoang sơ",
                            MinPrice = 4500000m,
                            Name = "Tour Côn Đảo"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Code = "PQ002",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Description = "Trải nghiệm biển đảo yên bình",
                            MinPrice = 3000000m,
                            Name = "Tour Đảo Phú Quý"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Code = "NT003",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "Hà Nội",
                            Description = "Biển xanh & vui chơi giải trí",
                            MinPrice = 5200000m,
                            Name = "Tour Nha Trang"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Code = "PQ004",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocation = "TP.HCM",
                            Description = "Đảo ngọc nghỉ dưỡng cao cấp",
                            MinPrice = 3800000m,
                            Name = "Tour Phú Quốc"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.TourImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("TourId");

                    b.ToTable("TourImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrimary = true,
                            MediaAssetId = 1,
                            SortOrder = 1,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsPrimary = false,
                            MediaAssetId = 2,
                            SortOrder = 2,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsPrimary = false,
                            MediaAssetId = 3,
                            SortOrder = 3,
                            TourId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsPrimary = true,
                            MediaAssetId = 4,
                            SortOrder = 1,
                            TourId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsPrimary = false,
                            MediaAssetId = 5,
                            SortOrder = 2,
                            TourId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsPrimary = false,
                            MediaAssetId = 6,
                            SortOrder = 3,
                            TourId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsPrimary = true,
                            MediaAssetId = 7,
                            SortOrder = 1,
                            TourId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsPrimary = false,
                            MediaAssetId = 8,
                            SortOrder = 2,
                            TourId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsPrimary = false,
                            MediaAssetId = 9,
                            SortOrder = 3,
                            TourId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsPrimary = true,
                            MediaAssetId = 10,
                            SortOrder = 1,
                            TourId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsPrimary = false,
                            MediaAssetId = 11,
                            SortOrder = 2,
                            TourId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsPrimary = false,
                            MediaAssetId = 12,
                            SortOrder = 3,
                            TourId = 4
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.TourSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdultPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("ChildPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultPrice = 4500000m,
                            AvailableSeats = 10,
                            ChildPrice = 3000000m,
                            DepartureDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available",
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdultPrice = 3000000m,
                            AvailableSeats = 0,
                            ChildPrice = 2000000m,
                            DepartureDate = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Full",
                            TourId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdultPrice = 5200000m,
                            AvailableSeats = 5,
                            ChildPrice = 3500000m,
                            DepartureDate = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available",
                            TourId = 3
                        },
                        new
                        {
                            Id = 4,
                            AdultPrice = 3800000m,
                            AvailableSeats = 0,
                            ChildPrice = 2500000m,
                            DepartureDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TourId = 4
                        },
                        new
                        {
                            Id = 5,
                            AdultPrice = 900000m,
                            AvailableSeats = 8,
                            ChildPrice = 600000m,
                            DepartureDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available",
                            TourId = 1
                        },
                        new
                        {
                            Id = 6,
                            AdultPrice = 4700000m,
                            AvailableSeats = 0,
                            ChildPrice = 3000000m,
                            DepartureDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Full",
                            TourId = 2
                        },
                        new
                        {
                            Id = 7,
                            AdultPrice = 3200000m,
                            AvailableSeats = 12,
                            ChildPrice = 2000000m,
                            DepartureDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available",
                            TourId = 3
                        },
                        new
                        {
                            Id = 8,
                            AdultPrice = 3100000m,
                            AvailableSeats = 0,
                            ChildPrice = 2000000m,
                            DepartureDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TourId = 4
                        },
                        new
                        {
                            Id = 9,
                            AdultPrice = 5500000m,
                            AvailableSeats = 7,
                            ChildPrice = 3500000m,
                            DepartureDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available",
                            TourId = 1
                        },
                        new
                        {
                            Id = 10,
                            AdultPrice = 700000m,
                            AvailableSeats = 3,
                            ChildPrice = 500000m,
                            DepartureDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quota = 20,
                            ReturnDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available",
                            TourId = 2
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 9000000m,
                            BookingId = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPay",
                            Status = "Success",
                            TransactionCode = "TRANS001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 6000000m,
                            BookingId = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Momo",
                            Status = "Pending",
                            TransactionCode = "TRANS002"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 10400000m,
                            BookingId = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPay",
                            Status = "Failed",
                            TransactionCode = "TRANS003"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 7600000m,
                            BookingId = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPay",
                            Status = "Failed",
                            TransactionCode = "TRANS004"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2700000m,
                            BookingId = 5,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Momo",
                            Status = "Success",
                            TransactionCode = "TRANS005"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 9400000m,
                            BookingId = 6,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPay",
                            Status = "Pending",
                            TransactionCode = "TRANS006"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 6400000m,
                            BookingId = 7,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Momo",
                            Status = "Success",
                            TransactionCode = "TRANS007"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 3100000m,
                            BookingId = 8,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPay",
                            Status = "Failed",
                            TransactionCode = "TRANS008"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 11000000m,
                            BookingId = 9,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPay",
                            Status = "Success",
                            TransactionCode = "TRANS009"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1400000m,
                            BookingId = 10,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Momo",
                            Status = "Pending",
                            TransactionCode = "TRANS010"
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a@gmail.com",
                            FullName = "Nguyễn Văn A",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000001",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "b@gmail.com",
                            FullName = "Trần Thị B",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000002",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "c@gmail.com",
                            FullName = "Lê Văn C",
                            IsLocked = true,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000003",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "d@gmail.com",
                            FullName = "Phạm Thị D",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000004",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "e@gmail.com",
                            FullName = "Hoàng Văn E",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000005",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "f@gmail.com",
                            FullName = "Đỗ Thị F",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000006",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "g@gmail.com",
                            FullName = "Võ Văn G",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000007",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "h@gmail.com",
                            FullName = "Bùi Thị H",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000008",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "i@gmail.com",
                            FullName = "Ngô Văn I",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "090000009",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@travel.com",
                            FullName = "Admin",
                            IsLocked = false,
                            PasswordHash = "$2a$11$5JCEuIAPe01M9Hz0jahT9.ZfJKi2Vl9iRe6ICMhY10bgnRQ4yA.FW",
                            Phone = "0999999999",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SUMMER10",
                            DiscountType = "Percentage",
                            DiscountValue = 10m,
                            ExpiryDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Code = "SALE200K",
                            DiscountType = "FixedAmount",
                            DiscountValue = 200000m,
                            ExpiryDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Code = "NEWUSER",
                            DiscountType = "Percentage",
                            DiscountValue = 15m,
                            ExpiryDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Code = "VIP500K",
                            DiscountType = "FixedAmount",
                            DiscountValue = 500000m,
                            ExpiryDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 10
                        },
                        new
                        {
                            Id = 5,
                            Code = "HOLIDAY",
                            DiscountType = "Percentage",
                            DiscountValue = 20m,
                            ExpiryDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Code = "FLASH",
                            DiscountType = "FixedAmount",
                            DiscountValue = 100000m,
                            ExpiryDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 40
                        },
                        new
                        {
                            Id = 7,
                            Code = "WEEKEND",
                            DiscountType = "Percentage",
                            DiscountValue = 5m,
                            ExpiryDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 60
                        },
                        new
                        {
                            Id = 8,
                            Code = "TRAVEL50",
                            DiscountType = "FixedAmount",
                            DiscountValue = 50000m,
                            ExpiryDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 80
                        },
                        new
                        {
                            Id = 9,
                            Code = "FAMILY",
                            DiscountType = "Percentage",
                            DiscountValue = 12m,
                            ExpiryDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 25
                        },
                        new
                        {
                            Id = 10,
                            Code = "LASTMIN",
                            DiscountType = "Percentage",
                            DiscountValue = 8m,
                            ExpiryDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("TravelTour.API.Models.Booking", b =>
                {
                    b.HasOne("TravelTour.API.Models.TourSchedule", "TourSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("TourScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.Voucher", "Voucher")
                        .WithMany("Bookings")
                        .HasForeignKey("VoucherId");

                    b.Navigation("TourSchedule");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("TravelTour.API.Models.BookingAttendee", b =>
                {
                    b.HasOne("TravelTour.API.Models.Booking", "Booking")
                        .WithMany("BookingAttendees")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelTour.API.Models.MediaAsset", b =>
                {
                    b.HasOne("TravelTour.API.Models.User", "UploadedBy")
                        .WithMany("UploadedMediaAssets")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsPost", b =>
                {
                    b.HasOne("TravelTour.API.Models.User", "Author")
                        .WithMany("AuthoredNewsPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.NewsCategory", "Category")
                        .WithMany("NewsPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.User", "PublishedBy")
                        .WithMany("PublishedNewsPosts")
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("PublishedBy");
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsTagMap", b =>
                {
                    b.HasOne("TravelTour.API.Models.NewsPost", "NewsPost")
                        .WithMany("NewsTagMaps")
                        .HasForeignKey("NewsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.NewsTag", "NewsTag")
                        .WithMany("NewsTagMaps")
                        .HasForeignKey("NewsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsPost");

                    b.Navigation("NewsTag");
                });

            modelBuilder.Entity("TravelTour.API.Models.Review", b =>
                {
                    b.HasOne("TravelTour.API.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelTour.API.Models.Tour", b =>
                {
                    b.HasOne("TravelTour.API.Models.Category", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TravelTour.API.Models.TourImage", b =>
                {
                    b.HasOne("TravelTour.API.Models.MediaAsset", "MediaAsset")
                        .WithMany("TourImages")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTour.API.Models.Tour", "Tour")
                        .WithMany("TourImages")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelTour.API.Models.TourSchedule", b =>
                {
                    b.HasOne("TravelTour.API.Models.Tour", "Tour")
                        .WithMany("TourSchedules")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelTour.API.Models.Transaction", b =>
                {
                    b.HasOne("TravelTour.API.Models.Booking", "Booking")
                        .WithMany("Transactions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelTour.API.Models.User", b =>
                {
                    b.HasOne("TravelTour.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TravelTour.API.Models.Booking", b =>
                {
                    b.Navigation("BookingAttendees");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TravelTour.API.Models.Category", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelTour.API.Models.MediaAsset", b =>
                {
                    b.Navigation("TourImages");
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsCategory", b =>
                {
                    b.Navigation("NewsPosts");
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsPost", b =>
                {
                    b.Navigation("NewsTagMaps");
                });

            modelBuilder.Entity("TravelTour.API.Models.NewsTag", b =>
                {
                    b.Navigation("NewsTagMaps");
                });

            modelBuilder.Entity("TravelTour.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TravelTour.API.Models.Tour", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("TourImages");

                    b.Navigation("TourSchedules");
                });

            modelBuilder.Entity("TravelTour.API.Models.TourSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TravelTour.API.Models.User", b =>
                {
                    b.Navigation("AuthoredNewsPosts");

                    b.Navigation("Bookings");

                    b.Navigation("PublishedNewsPosts");

                    b.Navigation("Reviews");

                    b.Navigation("UploadedMediaAssets");
                });

            modelBuilder.Entity("TravelTour.API.Models.Voucher", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
